# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'H:\Diplom\gui\main.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(907, 796)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(907, 796))
        MainWindow.setMaximumSize(QtCore.QSize(907, 796))
        MainWindow.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.selectFile = QtWidgets.QPushButton(self.centralwidget)
        self.selectFile.setGeometry(QtCore.QRect(540, 50, 81, 21))
        self.selectFile.setObjectName("selectFile")
        self.profilesBox = QtWidgets.QComboBox(self.centralwidget)
        self.profilesBox.setGeometry(QtCore.QRect(10, 50, 251, 21))
        self.profilesBox.setObjectName("profilesBox")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 5, 291, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.fileName = QtWidgets.QLineEdit(self.centralwidget)
        self.fileName.setEnabled(True)
        self.fileName.setGeometry(QtCore.QRect(310, 50, 221, 21))
        self.fileName.setAcceptDrops(True)
        self.fileName.setFrame(True)
        self.fileName.setReadOnly(True)
        self.fileName.setClearButtonEnabled(False)
        self.fileName.setObjectName("fileName")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(310, 0, 341, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(310, 80, 341, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.bookName = QtWidgets.QLineEdit(self.centralwidget)
        self.bookName.setGeometry(QtCore.QRect(310, 120, 221, 31))
        self.bookName.setObjectName("bookName")
        self.AddButton = QtWidgets.QPushButton(self.centralwidget)
        self.AddButton.setGeometry(QtCore.QRect(540, 120, 81, 31))
        self.AddButton.setObjectName("AddButton")
        self.ErrorLabel = QtWidgets.QLabel(self.centralwidget)
        self.ErrorLabel.setGeometry(QtCore.QRect(310, 150, 341, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.ErrorLabel.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.ErrorLabel.setFont(font)
        self.ErrorLabel.setText("")
        self.ErrorLabel.setObjectName("ErrorLabel")
        self.TextBlobButton = QtWidgets.QPushButton(self.centralwidget)
        self.TextBlobButton.setGeometry(QtCore.QRect(120, 170, 141, 31))
        self.TextBlobButton.setObjectName("TextBlobButton")
        self.VADERButton = QtWidgets.QPushButton(self.centralwidget)
        self.VADERButton.setGeometry(QtCore.QRect(120, 220, 141, 31))
        self.VADERButton.setObjectName("VADERButton")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 80, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.speakersSlider = QtWidgets.QSlider(self.centralwidget)
        self.speakersSlider.setGeometry(QtCore.QRect(30, 130, 21, 171))
        self.speakersSlider.setOrientation(QtCore.Qt.Vertical)
        self.speakersSlider.setObjectName("speakersSlider")
        self.maxLabel = QtWidgets.QLabel(self.centralwidget)
        self.maxLabel.setGeometry(QtCore.QRect(16, 110, 51, 20))
        self.maxLabel.setText("0")
        self.maxLabel.setTextFormat(QtCore.Qt.AutoText)
        self.maxLabel.setScaledContents(False)
        self.maxLabel.setObjectName("maxLabel")
        self.minLabel = QtWidgets.QLabel(self.centralwidget)
        self.minLabel.setGeometry(QtCore.QRect(9, 300, 61, 20))
        self.minLabel.setObjectName("minLabel")
        self.curLabel = QtWidgets.QLabel(self.centralwidget)
        self.curLabel.setGeometry(QtCore.QRect(70, 130, 31, 171))
        self.curLabel.setObjectName("curLabel")
        self.socialButton = QtWidgets.QPushButton(self.centralwidget)
        self.socialButton.setGeometry(QtCore.QRect(120, 120, 141, 31))
        self.socialButton.setObjectName("socialButton")
        self.unitedButton = QtWidgets.QPushButton(self.centralwidget)
        self.unitedButton.setGeometry(QtCore.QRect(120, 270, 141, 31))
        self.unitedButton.setObjectName("unitedButton")
        self.replicsTable = QtWidgets.QTableWidget(self.centralwidget)
        self.replicsTable.setGeometry(QtCore.QRect(10, 370, 221, 341))
        self.replicsTable.setObjectName("replicsTable")
        self.replicsTable.setColumnCount(2)
        self.replicsTable.setRowCount(10)
        item = QtWidgets.QTableWidgetItem()
        self.replicsTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.replicsTable.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.replicsTable.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.replicsTable.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.replicsTable.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.replicsTable.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.replicsTable.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.replicsTable.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.replicsTable.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.replicsTable.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.replicsTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.replicsTable.setHorizontalHeaderItem(1, item)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 320, 291, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.fromTable = QtWidgets.QTableWidget(self.centralwidget)
        self.fromTable.setGeometry(QtCore.QRect(300, 370, 221, 341))
        self.fromTable.setObjectName("fromTable")
        self.fromTable.setColumnCount(2)
        self.fromTable.setRowCount(10)
        item = QtWidgets.QTableWidgetItem()
        self.fromTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.fromTable.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.fromTable.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.fromTable.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.fromTable.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.fromTable.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.fromTable.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.fromTable.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.fromTable.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.fromTable.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.fromTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.fromTable.setHorizontalHeaderItem(1, item)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(300, 320, 291, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.toTable = QtWidgets.QTableWidget(self.centralwidget)
        self.toTable.setGeometry(QtCore.QRect(590, 370, 221, 341))
        self.toTable.setObjectName("toTable")
        self.toTable.setColumnCount(2)
        self.toTable.setRowCount(10)
        item = QtWidgets.QTableWidgetItem()
        self.toTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.toTable.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.toTable.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.toTable.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.toTable.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.toTable.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.toTable.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.toTable.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.toTable.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.toTable.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.toTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.toTable.setHorizontalHeaderItem(1, item)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(590, 320, 291, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(300, 200, 381, 31))
        self.label_4.setObjectName("label_4")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(300, 230, 381, 31))
        self.label_9.setObjectName("label_9")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 907, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Machine Learning Literature Analyzer"))
        self.selectFile.setText(_translate("MainWindow", "Выбор файла"))
        self.label.setText(_translate("MainWindow", "Выберите анализируемое \n"
"произведение:"))
        self.label_2.setText(_translate("MainWindow", "Выберите файл с текстом произведения:"))
        self.label_3.setText(_translate("MainWindow", "Введите наименование произведения:"))
        self.AddButton.setText(_translate("MainWindow", "Добавить "))
        self.TextBlobButton.setText(_translate("MainWindow", "Text Blob граф отношений"))
        self.VADERButton.setText(_translate("MainWindow", "VADER граф отношений"))
        self.label_5.setText(_translate("MainWindow", "Графы:"))
        self.minLabel.setText(_translate("MainWindow", "0"))
        self.curLabel.setText(_translate("MainWindow", "0"))
        self.socialButton.setText(_translate("MainWindow", "Граф социальных связей"))
        self.unitedButton.setText(_translate("MainWindow", "Объединённый граф"))
        item = self.replicsTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Имя"))
        item = self.replicsTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Количество"))
        self.label_6.setText(_translate("MainWindow", "Топ 10 по количеству\n"
" произнесенных реплик:"))
        item = self.fromTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Имя"))
        item = self.fromTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Количество"))
        self.label_7.setText(_translate("MainWindow", "Топ 10 по количеству обращений \n"
"к разным персонажам:"))
        item = self.toTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Имя"))
        item = self.toTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Количество"))
        self.label_8.setText(_translate("MainWindow", "Топ 10 по количеству персонажей,\n"
"которые обращались к данному:"))
        self.label_4.setText(_translate("MainWindow", "Не рекомендуется построение графа отношений и объединённого графа \n"
"для более чем 20 персонажей. Это может вызвать искажение в данных."))
        self.label_9.setText(_translate("MainWindow", "Построение графов может занимать до минуты , в зависимости от \n"
"количества выбранных персонажей."))
